### ISSUE TITLE
Kernel fails to build on Linux/Nvidia

### ISSUE THREAD

**Issue by ghost** [lbryio/lbrycrd-gpu#2]
Is Nvidia even supported by this miner? The readme doesn't say...

Using Cuda 7.5

<pre>
./kernel/wolf-sha512.cl:55:69: warning: implicit declaration of function 'amd_bitalign' is invalid in C99
ulong FAST_ROTR64_LO(const uint2 x, const uint y) { return(as_ulong(amd_bitalign(x.s10, x, y))); }
                                                                    ^
./kernel/wolf-sha512.cl:55:60: error: call to 'as_ulong' is ambiguous
ulong FAST_ROTR64_LO(const uint2 x, const uint y) { return(as_ulong(amd_bitalign(x.s10, x, y))); }
                                                           ^~~~~~~~
cl_kernel.h:14906:24: note: candidate function
ulong __OVERLOADABLE__ as_ulong (long);
                       ^
cl_kernel.h:14907:24: note: candidate function
ulong __OVERLOADABLE__ as_ulong (ulong);
                       ^
cl_kernel.h:14908:24: note: candidate function
ulong __OVERLOADABLE__ as_ulong (double);
                       ^
cl_kernel.h:15584:24: note: candidate function
ulong __OVERLOADABLE__ as_ulong (char8);
                       ^
cl_kernel.h:15585:24: note: candidate function
ulong __OVERLOADABLE__ as_ulong (uchar8);
                       ^
cl_kernel.h:15587:24: note: candidate function
ulong __OVERLOADABLE__ as_ulong (short3);
                       ^
cl_kernel.h:15589:24: note: candidate function
ulong __OVERLOADABLE__ as_ulong (short4);
                       ^
cl_kernel.h:15591:24: note: candidate function
ulong __OVERLOADABLE__ as_ulong (ushort3);
                       ^
cl_kernel.h:15593:24: note: candidate function
ulong __OVERLOADABLE__ as_ulong (ushort4);
                       ^
cl_kernel.h:15594:24: note: candidate function
ulong __OVERLOADABLE__ as_ulong (int2);
                       ^
cl_kernel.h:15595:24: note: candidate function
ulong __OVERLOADABLE__ as_ulong (uint2);
                       ^
cl_kernel.h:15596:24: note: candidate function
ulong __OVERLOADABLE__ as_ulong (float2);
                       ^
In file included from <kernel>:2:
./kernel/wolf-sha512.cl:56:60: error: call to 'as_ulong' is ambiguous
ulong FAST_ROTR64_HI(const uint2 x, const uint y) { return(as_ulong(amd_bitalign(x, x.s10, (y - 32)))); }
                                                           ^~~~~~~~
cl_kernel.h:14906:24: note: candidate function
ulong __OVERLOADABLE__ as_ulong (long);
                       ^
cl_kernel.h:14907:24: note: candidate function
ulong __OVERLOADABLE__ as_ulong (ulong);
                       ^
cl_kernel.h:14908:24: note: candidate function
ulong __OVERLOADABLE__ as_ulong (double);
                       ^
cl_kernel.h:15584:24: note: candidate function
ulong __OVERLOADABLE__ as_ulong (char8);
                       ^
cl_kernel.h:15585:24: note: candidate function
ulong __OVERLOADABLE__ as_ulong (uchar8);
                       ^
cl_kernel.h:15587:24: note: candidate function
ulong __OVERLOADABLE__ as_ulong (short3);
                       ^
cl_kernel.h:15589:24: note: candidate function
ulong __OVERLOADABLE__ as_ulong (short4);
                       ^
cl_kernel.h:15591:24: note: candidate function
ulong __OVERLOADABLE__ as_ulong (ushort3);
                       ^
cl_kernel.h:15593:24: note: candidate function
ulong __OVERLOADABLE__ as_ulong (ushort4);
                       ^
cl_kernel.h:15594:24: note: candidate function
ulong __OVERLOADABLE__ as_ulong (int2);
                       ^
cl_kernel.h:15595:24: note: candidate function
ulong __OVERLOADABLE__ as_ulong (uint2);
                       ^
cl_kernel.h:15596:24: note: candidate function
ulong __OVERLOADABLE__ as_ulong (float2);
                       ^
In file included from <kernel>:3:
./kernel/ripemd160.cl:5:9: warning: 'F1' macro redefined
#define F1(x, y, z)     ((x) ^ (y) ^ (z))
        ^
./kernel/sha256.cl:18:9: note: previous definition is here
#define F1(x, y, z) bitselect(z, y, x)
        ^
<kernel>:5:9: warning: 'SWAP32' macro redefined
#define SWAP32(x)               as_uint(as_uchar4(x).s3210)
        ^
./kernel/sha256.cl:3:9: note: previous definition is here
#define SWAP32(a)       (as_uint(as_uchar4(a).wzyx))
        ^
</pre>

**Comment by kimihiro64** [comment]
Nvidia is not supported for this miner, but a new miner for Nvidia cards is in testing and may be released as soon as next week.

**Comment by ghost** [comment]
Thanks! You may want to add that to the readme :)

**Comment by djoq** [comment]
Any updates on this?
