### ISSUE TITLE
Unable to open lbry.cl for reading

### ISSUE THREAD

**Issue by enstat** [lbryio/lbrycrd-gpu#8]
Startup Pool No = 0
Building binary lbryGeForce GTX 1080 Tigw256l4.bin
Unable to open lbry.cl for reading!
Failed to init GPU thread 0, disabling device 0
Restarting the GPU from the menu will not fix this.
Re-check your configuration and try restarting.
Press enter to continue:
-
How solve this problem?

**Comment by kauffj** [comment]
@wolf0 in [LBRY Slack](https://slack.lbry.io) says to use ccminer.

Maybe this article would help? https://steemit.com/beyondbitcoin/@contentjunkie/how-to-mine-lbry-credits-with-an-nvidia-gpu-on-windows

If having trouble, try DMing @wolf0 in our chat.
